[package]
name = "kinic-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
ic-agent = "0.44.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
